const $=s=>document.querySelector(s);const fileInput=$('#fileInput'),video=$('#video'),canvas=$('#canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
let file,selection=null,dragStart=null,frameImage=null,busy=false;
const controls={duration:$('#duration'),tolerance:$('#tolerance'),softness:$('#softness'),fps:$('#fps')};
$('#pickButton').onclick=()=>fileInput.click();$('#changeButton').onclick=()=>fileInput.click();fileInput.onchange=()=>loadFile(fileInput.files[0]);
const dz=$('#dropZone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('drag')}));dz.ondrop=e=>loadFile(e.dataTransfer.files[0]);
async function loadFile(f){if(!f||!f.type.startsWith('video/'))return alert('動画ファイルを選んでください。');file=f;video.src=URL.createObjectURL(f);await once(video,'loadedmetadata');canvas.width=Math.min(video.videoWidth,960);canvas.height=Math.round(canvas.width*video.videoHeight/video.videoWidth);$('#fileName').textContent=f.name;$('#videoMeta').textContent=`${video.videoWidth}×${video.videoHeight} / ${video.duration.toFixed(1)}秒`;$('#timeline').max=1000;$('#dropZone').classList.add('hidden');$('#workspace').classList.remove('hidden');selection=null;await seek(0);}
function once(el,event){return new Promise(r=>el.addEventListener(event,r,{once:true}))}async function seek(t){video.currentTime=Math.max(0,Math.min(t,video.duration-.01));await once(video,'seeked');drawFrame()}
function drawFrame(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(video,0,0,canvas.width,canvas.height);frameImage=ctx.getImageData(0,0,canvas.width,canvas.height);if(selection){ctx.strokeStyle='#ff5c8a';ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.strokeRect(selection.x,selection.y,selection.w,selection.h);ctx.setLineDash([])}}
$('#timeline').oninput=()=>seek(video.duration*$('#timeline').value/1000);
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.onpointerdown=e=>{dragStart=pos(e);selection=null;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!dragStart)return;const p=pos(e);selection={x:Math.min(p.x,dragStart.x),y:Math.min(p.y,dragStart.y),w:Math.abs(p.x-dragStart.x),h:Math.abs(p.y-dragStart.y)};drawFrame()};canvas.onpointerup=()=>{dragStart=null;if(selection&&selection.w>12&&selection.h>12){$('#hint').textContent='選択できました。プレビューで確認してください';$('#previewButton').disabled=$('#exportButton').disabled=false}};
function buildMask(image,sel){const {width:w,height:h,data}=image,tol=+controls.tolerance.value;const samples=[];for(let y=sel.y+sel.h*.18;y<sel.y+sel.h*.82;y+=Math.max(3,sel.h/18))for(let x=sel.x+sel.w*.18;x<sel.x+sel.w*.82;x+=Math.max(3,sel.w/18)){let i=(Math.floor(y)*w+Math.floor(x))*4;samples.push([data[i],data[i+1],data[i+2]])}const mask=new Uint8Array(w*h);const pad=Math.max(sel.w,sel.h)*.18,x0=Math.max(0,sel.x-pad),x1=Math.min(w,sel.x+sel.w+pad),y0=Math.max(0,sel.y-pad),y1=Math.min(h,sel.y+sel.h+pad);for(let y=y0|0;y<y1;y++)for(let x=x0|0;x<x1;x++){let i=(y*w+x)*4,best=1e9;for(const c of samples){const d=Math.abs(data[i]-c[0])+Math.abs(data[i+1]-c[1])+Math.abs(data[i+2]-c[2]);if(d<best)best=d}if(best<tol*3)mask[y*w+x]=255}return mask}
function cutout(image,sel,out=ctx){const mask=buildMask(image,sel),d=image.data,soft=+controls.softness.value;for(let i=0;i<mask.length;i++)d[i*4+3]=mask[i];out.clearRect(0,0,canvas.width,canvas.height);out.putImageData(image,0,0);if(soft){out.save();out.globalCompositeOperation='destination-in';out.filter=`blur(${soft}px)`;out.drawImage(canvas,0,0);out.restore();out.filter='none'}}
$('#previewButton').onclick=()=>{const img=new ImageData(new Uint8ClampedArray(frameImage.data),frameImage.width,frameImage.height);cutout(img,selection);$('#hint').textContent='プレビュー中。タイムラインを動かすと元に戻ります'};
async function processFrames(onFrame){if(busy)return;busy=true;toggle(true);const start=video.currentTime,dur=Math.min(+controls.duration.value,video.duration-start),fps=+controls.fps.value,total=Math.max(1,Math.floor(dur*fps));const base={...selection};try{for(let n=0;n<total;n++){await seek(start+n/fps);const img=ctx.getImageData(0,0,canvas.width,canvas.height);cutout(img,base);$('#hint').textContent=`処理中 ${n+1} / ${total}`;await onFrame(n,total)}}finally{busy=false;toggle(false);$('#hint').textContent='対象キャラをドラッグで囲んでください'}}
function toggle(v){document.querySelectorAll('button').forEach(b=>{if(b.id!=='changeButton')b.disabled=v})}
$('#exportButton').onclick=async()=>{const stream=canvas.captureStream(+controls.fps.value),chunks=[],mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm',rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:5_000_000});rec.ondataavailable=e=>chunks.push(e.data);rec.start();await processFrames(async()=>new Promise(r=>setTimeout(r,1000/+controls.fps.value)));rec.stop();await once(rec,'stop');showResult(new Blob(chunks,{type:mime}),'webm','背景透過対応のWebMです。対応ソフトで重ねて使えます。')};
function showResult(blob,ext,note){const url=URL.createObjectURL(blob),link=$('#downloadLink');$('#result').classList.remove('hidden');$('#resultNote').textContent=note;link.href=url;link.download=`anime-cutout.${ext}`;link.textContent=`${ext.toUpperCase()}を保存`;$('#resultVideo').style.display=ext==='webm'?'block':'none';if(ext==='webm')$('#resultVideo').src=url;$('#result').scrollIntoView({behavior:'smooth'})}
for(const [id,suffix] of [['duration','秒'],['tolerance',''],['softness','px']])controls[id].oninput=()=>$('#'+id+'Value').textContent=controls[id].value+suffix;
